name: muna
description: Run AI models in Flutter. Register at https://muna.ai.
version: 0.0.1
homepage: https://muna.ai
repository: https://github.com/muna-ai/muna-flutter
documentation: https://docs.muna.ai
issue_tracker: https://github.com/muna-ai/muna-flutter/issues
topics:
  - ai
  - machine-learning
  - inference

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  crypto: ^3.0.6
  ffi: ^2.1.4
  http: ^1.3.0

flutter:
  plugin:
    platforms:
      android:
      ios:
      macos:
      windows:
      linux:

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.8
